### PR TITLE
Be safe about localStorage access. Fixes #10

### LINKED ISSUE #10: Unsafe usage of localStorage
https://github.com/mapbox/mapbox-events/blob/master/index.js#L43-L53

This code will fail in browsers configured to disallow localStorage: these browsers will pass the check for localStorage being present, but throw when you interact with localStorage. The set/get calls should be included in the try/catch block.

### PR DESCRIPTION
**Pull request by tmcw**

### CODE REVIEW

**Comment by camilleanne** [comment]
I bet this would also fix https://github.com/mapbox/mapbox-events/issues/8

**Comment by tmcw** [comment]
If localStorage is not available, this'll still give you a null anonid - if we wanted anonid to be a session-long variable instead, we should probably assign `this.anonid = hat()` or something like that instead.

**Comment by camilleanne** [comment]
Client side tests in Instrumentile aren't passing for this -- will merge once I've debugged a bit.

**Comment by camilleanne** [comment]
So begins the long deploy:
- [x] tag mapbox-events
- [x] pr and tag instrumentile
- [x] pr, test like crazy, and tag mapbox-maps-embed
- [x] pr and tag mapbox-maps
- [x] pr and deploy api-maps

**Pull request merged**
